In [1]:
# libraries -----------------------------------------------------------------

import requests 
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
# get data ----------------------------------------------------

df = pd.read_csv('ebola_data_db_format.csv', 
                 parse_dates=['Date'])
df.head()

,Indicator,Country,Date,value
0,"Cumulative number of confirmed, probable and s...",Guinea,2015-03-10,3285.0
1,Cumulative number of confirmed Ebola cases,Guinea,2015-03-10,2871.0
2,Cumulative number of probable Ebola cases,Guinea,2015-03-10,392.0
3,Cumulative number of suspected Ebola cases,Guinea,2015-03-10,22.0
4,"Cumulative number of confirmed, probable and s...",Guinea,2015-03-10,2170.0

In [3]:
df.shape

(17585, 4)

In [4]:
df['Indicator'].value_counts()

Cumulative number of confirmed, probable and suspected Ebola deaths                            2485
Cumulative number of confirmed Ebola cases                                                     2484
Cumulative number of confirmed, probable and suspected Ebola cases                             2477
Cumulative number of probable Ebola cases                                                      2436
Cumulative number of suspected Ebola cases                                                     2366
Cumulative number of confirmed Ebola deaths                                                    1648
Cumulative number of probable Ebola deaths                                                     1526
Cumulative number of suspected Ebola deaths                                                    1308
Number of confirmed, probable and suspected Ebola cases in the last 21 days                     190
Number of confirmed Ebola cases in the last 21 days                                             190
Number of probable Ebola cases in the last 21 days                                               52
Proportion of confirmed, probable and suspected Ebola cases that are from the last 21 days       41
Proportion of probable Ebola cases that are from the last 21 days                                40
Proportion of confirmed Ebola cases that are from the last 21 days                               40
Number of suspected Ebola cases in the last 21 days                                              39
Proportion of suspected Ebola cases that are from the last 21 days                               39
Case fatality rate (CFR) of confirmed Ebola cases                                                19
Case fatality rate (CFR) of confirmed, probable and suspected Ebola cases                        19
Case fatality rate (CFR) of suspected Ebola cases                                                18
Case fatality rate (CFR) of probable Ebola cases                                                 18
Number of confirmed, probable and suspected Ebola deaths in the last 21 days                     14
Number of confirmed Ebola deaths in the last 21 days                                             14
Number of probable Ebola deaths in the last 21 days                                              13
Number of suspected Ebola deaths in the last 21 days                                             13
Proportion of confirmed, probable and suspected Ebola deaths that are from the last 21 days      13
Proportion of confirmed Ebola deaths that are from the last 21 days                              13
Proportion of probable Ebola deaths that are from the last 21 days                               12
Proportion of suspected Ebola deaths that are from the last 21 days                              10
Number of confirmed Ebola cases in the last 7 days                                                6
Number of confirmed, probable and suspected Ebola cases in the last 7 days                        6
Number of suspected Ebola cases in the last 7 days                                                6
Number of probable Ebola cases in the last 7 days                                                 6
Proportion of confirmed Ebola cases that are from the last 7 days                                 6
Proportion of suspected Ebola cases that are from the last 7 days                                 6
Proportion of probable Ebola cases that are from the last 7 days                                  6
Proportion of confirmed, probable and suspected Ebola cases that are from the last 7 days         6
Name: Indicator, dtype: int64

In [5]:
df = df[(df['Indicator']=='Cumulative number of confirmed, probable and suspected Ebola cases')|
        (df['Indicator']=='Cumulative number of confirmed, probable and suspected Ebola deaths')|
        (df['Indicator']=='Cumulative number of suspected Ebola cases')|
        (df['Indicator']=='Cumulative number of suspected Ebola deaths')|
        (df['Indicator']=='Cumulative number of probable Ebola cases')|
        (df['Indicator']=='Cumulative number of probable Ebola deaths')|
        (df['Indicator']=='Cumulative number of confirmed Ebola cases')|
        (df['Indicator']=='Cumulative number of confirmed Ebola deaths')].reset_index(drop=True)
df.head()

,Indicator,Country,Date,value
0,"Cumulative number of confirmed, probable and s...",Guinea,2015-03-10,3285.0
1,Cumulative number of confirmed Ebola cases,Guinea,2015-03-10,2871.0
2,Cumulative number of probable Ebola cases,Guinea,2015-03-10,392.0
3,Cumulative number of suspected Ebola cases,Guinea,2015-03-10,22.0
4,"Cumulative number of confirmed, probable and s...",Guinea,2015-03-10,2170.0

In [6]:
final_df = df.pivot_table(values='value', index=['Country', 'Date'], columns=['Indicator'])
final_df = final_df.reset_index()
final_df = final_df.sort_values('Date').reset_index(drop=True)
final_df.rename_axis(None)
final_df.head()

Indicator,Country,Date,Cumulative number of confirmed Ebola cases,Cumulative number of confirmed Ebola deaths,"Cumulative number of confirmed, probable and suspected Ebola cases","Cumulative number of confirmed, probable and suspected Ebola deaths",Cumulative number of probable Ebola cases,Cumulative number of probable Ebola deaths,Cumulative number of suspected Ebola cases,Cumulative number of suspected Ebola deaths
0,Guinea,2014-08-29,482.0,287.0,648.0,430.0,141.0,141.0,25.0,2.0
1,Nigeria,2014-08-29,15.0,6.0,19.0,7.0,1.0,1.0,3.0,0.0
2,Sierra Leone,2014-08-29,935.0,380.0,1026.0,422.0,37.0,34.0,54.0,8.0
3,Liberia,2014-08-29,322.0,225.0,1378.0,694.0,674.0,301.0,382.0,168.0
4,Sierra Leone,2014-09-05,1146.0,443.0,1261.0,491.0,37.0,37.0,78.0,11.0

In [7]:
final_df.columns

Index(['Country', 'Date', 'Cumulative number of confirmed Ebola cases',
       'Cumulative number of confirmed Ebola deaths',
       'Cumulative number of confirmed, probable and suspected Ebola cases',
       'Cumulative number of confirmed, probable and suspected Ebola deaths',
       'Cumulative number of probable Ebola cases',
       'Cumulative number of probable Ebola deaths',
       'Cumulative number of suspected Ebola cases',
       'Cumulative number of suspected Ebola deaths'],
      dtype='object', name='Indicator')

In [8]:
final_df = final_df[['Country', 'Date', 'Cumulative number of suspected Ebola cases', 
                     'Cumulative number of probable Ebola cases', 'Cumulative number of confirmed Ebola cases', 
                     'Cumulative number of confirmed, probable and suspected Ebola cases',
                     'Cumulative number of suspected Ebola deaths', 'Cumulative number of probable Ebola deaths', 
                     'Cumulative number of confirmed Ebola deaths', 
                     'Cumulative number of confirmed, probable and suspected Ebola deaths']]

In [9]:
final_df.columns = ['Country', 'Date', 'No. of suspected cases', 
                     'No. of probable cases', 'No. of confirmed cases', 
                     'No. of confirmed, probable and suspected cases',
                     'No. of suspected deaths', 'No. of probable deaths', 
                     'No. of confirmed deaths', 
                     'No. of confirmed, probable and suspected deaths']

In [10]:
final_df.head()

,Country,Date,No. of suspected cases,No. of probable cases,No. of confirmed cases,"No. of confirmed, probable and suspected cases",No. of suspected deaths,No. of probable deaths,No. of confirmed deaths,"No. of confirmed, probable and suspected deaths"
0,Guinea,2014-08-29,25.0,141.0,482.0,648.0,2.0,141.0,287.0,430.0
1,Nigeria,2014-08-29,3.0,1.0,15.0,19.0,0.0,1.0,6.0,7.0
2,Sierra Leone,2014-08-29,54.0,37.0,935.0,1026.0,8.0,34.0,380.0,422.0
3,Liberia,2014-08-29,382.0,674.0,322.0,1378.0,168.0,301.0,225.0,694.0
4,Sierra Leone,2014-09-05,78.0,37.0,1146.0,1261.0,11.0,37.0,443.0,491.0

In [14]:
final_df['Country'].value_counts().sort_index()

Guinea                      259
Italy                       141
Liberia                     365
Mali                        243
Nigeria                     255
Senegal                     254
Sierra Leone                259
Spain                       243
United Kingdom              221
United States of America    245
Name: Country, dtype: int64

In [12]:
final_df['Country'] = final_df['Country'].replace(r'Liberia 2', 'Liberia', regex=True)
final_df['Country'] = final_df['Country'].replace(r'Guinea 2', 'Liberia', regex=True)

In [15]:
final_df.to_csv('ebola_2014_2016_clean.csv', index=False)